# Jdbc Driver Settings
# パスワードを暗号化したいなどのニーズがある場合などは設定を外だしにすることも可能
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ixui-example?useSSL=false
    username: root
    password: Password_1
    driverClassName: com.mysql.cj.jdbc.Driver
